@startuml
'https://plantuml.com/class-diagram

left header 12 objects
title nCino 2023 Fall - Covenants Summary - AutoGen

'skinparam classBorderThickness 0

hide circle
hide empty methods
hide empty fields

'legend right
'  Relationship
'    M = MasterDetail
'    xn = n-times
'  Field
'    bold = required
'    underline = MasterDetail
'endlegend


entity CovenantRule as "<b>Covenant Rule</b> \nLLC_BI__Covenant_Rule__c"  {
}
entity CovenantType as "<b>Covenant Type</b> \nLLC_BI__Covenant_Type__c"  {
}
entity CovenantProduct as "<b>Covenant Product</b> \nLLC_BI__Covenant_Product__c"  {
}
entity CovenantMgmt as "<b>Covenant Mgmt</b> \nLLC_BI__Covenant2__c"  {
}
entity LoanCovenant as "<b>Loan Covenant</b> \nLLC_BI__Loan_Covenant__c"  {
}
entity Loan as "<b>Loan</b> \nLLC_BI__Loan__c"  {
}
entity PolicyException as "<b>Policy Exception</b> \nLLC_BI__Policy_Exception__c"  {
}
entity PricingCovenant as "<b>Pricing Covenant</b> \nLLC_BI__Pricing_Covenant__c"  {
}
entity Relationship as "<b>Relationship</b> \nAccount" #lightblue {
}
entity CovenantCompliance as "<b>Covenant Compliance</b> \nLLC_BI__Covenant_Compliance2__c"  {
}
entity AccountCovenant as "<b>Account Covenant</b> \nLLC_BI__Account_Covenant__c"  {
}
entity Contact as "<b>Contact</b> \nContact" #lightblue {
}

CovenantProduct }o--|| CovenantMgmt: M
Loan }o--o| Relationship: x2
PolicyException }o--o| Loan
Loan }o--o| Contact
CovenantMgmt }o--o| CovenantType
PricingCovenant }o--|| CovenantMgmt: M
PolicyException }o--o| Relationship
LoanCovenant }o--|| CovenantMgmt: M
CovenantCompliance }o--|| CovenantMgmt: M
CovenantMgmt }o--o| CovenantMgmt
CovenantRule }o--|| CovenantMgmt: M
AccountCovenant }o--|| Relationship: M
Loan }o--o| Loan: x3
LoanCovenant }o--|| Loan: M
AccountCovenant }o--o| Contact
Contact }o--o| Relationship
Contact }o--o| Contact: x2
AccountCovenant }o--|| CovenantMgmt: M
PolicyException }o--o| CovenantMgmt
CovenantMgmt }o--o| Relationship
Relationship }o--o| Relationship

@enduml
