@startuml
'https://plantuml.com/class-diagram

left header 13 objects
title nCino 2023 Fall - Collateral Summary - AutoGen

'skinparam classBorderThickness 0

hide circle
hide empty methods
hide empty fields

'legend right
'  Relationship
'    M = MasterDetail
'    xn = n-times
'  Field
'    bold = required
'    underline = MasterDetail
'endlegend


entity CollateralValuation as "<b>Collateral Valuation</b> \nLLC_BI__Collateral_Valuation__c"  {
}
entity ProductCollateralType as "<b>Product Collateral Type</b> \nLLC_BI__Product_Collateral_Type__c"  {
}
entity CollateralType as "<b>Collateral Type</b> \nLLC_BI__Collateral_Type__c"  {
}
entity CollateralMgmt as "<b>Collateral Mgmt</b> \nLLC_BI__Collateral__c"  {
}
entity CollateralGroup as "<b>Collateral Group</b> \nLLC_BI__Collateral_Group__c"  {
}
entity Lien as "<b>Lien</b> \nLLC_BI__Lien__c"  {
}
entity Collateral as "<b>Collateral</b> \nLLC_BI__Loan_Collateral__c"  {
}
entity CollateralOwnership as "<b>Collateral Ownership</b> \nLLC_BI__Account_Collateral__c"  {
}
entity Relationship as "<b>Relationship</b> \nAccount" #lightblue {
}
entity PolicyException as "<b>Policy Exception</b> \nLLC_BI__Policy_Exception__c"  {
}
entity Loan as "<b>Loan</b> \nLLC_BI__Loan__c"  {
}
entity LoanCollateralAggregate as "<b>Loan Collateral Aggregate</b> \nLLC_BI__Loan_Collateral_Aggregate__c"  {
}
entity CollateralPledged as "<b>Collateral Pledged</b> \nLLC_BI__Loan_Collateral2__c"  {
}

Lien }o--|| CollateralMgmt: M
CollateralPledged }o--|| LoanCollateralAggregate: M
Loan }o--o| Relationship: x2
PolicyException }o--o| Loan
PolicyException }o--o| Relationship
CollateralMgmt }o--o| Collateral
Loan }o--o| LoanCollateralAggregate
CollateralValuation }o--|| CollateralMgmt: M
Loan }o--o| Loan: x3
PolicyException }o--o| CollateralMgmt
CollateralMgmt }o--o| CollateralMgmt: x2
CollateralPledged }o--|| Loan
ProductCollateralType }o--|| CollateralType
CollateralOwnership }o--|| CollateralMgmt: M
Lien }o--o| Loan
CollateralMgmt }o--|| CollateralType
CollateralOwnership }o--|| Relationship: M
CollateralType }o--o| CollateralType: x2
Collateral }o--|| Loan: M
CollateralGroup }o--|| CollateralMgmt: x2
Relationship }o--o| Relationship
CollateralPledged }o--|| CollateralMgmt: M

@enduml
