@startuml
'https://plantuml.com/class-diagram

left header 22 objects
title nCino 2023 Fall - Product Package Summary - AutoGen

'skinparam classBorderThickness 0

hide circle
hide empty methods
hide empty fields

'legend right
'  Relationship
'    M = MasterDetail
'    xn = n-times
'  Field
'    bold = required
'    underline = MasterDetail
'endlegend


entity ConnectionRole as "<b>Connection Role</b> \nLLC_BI__Connection_Role__c"  {
}
entity Connection as "<b>Connection</b> \nLLC_BI__Connection__c"  {
}
entity Opportunity as "<b>Opportunity</b> \nOpportunity" #lightblue {
}
entity ProductPackageTeamMember as "<b>Product Package Team Member</b> \nLLC_BI__Product_Package_Team__c"  {
}
entity AuthorizedSigner as "<b>Authorized Signer</b> \nLLC_BI__Contingent_Liabilty__c"  {
}
entity Contact as "<b>Contact</b> \nContact" #lightblue {
}
entity Lead as "<b>Lead</b> \nLead" #lightblue {
}
entity Relationship as "<b>Relationship</b> \nAccount" #lightblue {
}
entity ProductPackage as "<b>Product Package</b> \nLLC_BI__Product_Package__c"  {
}
entity Deposit as "<b>Deposit</b> \nLLC_BI__Deposit__c"  {
}
entity Branch as "<b>Branch</b> \nLLC_BI__Branch__c"  {
}
entity ReviewAccount as "<b>Review Account</b> \nLLC_BI__Review_Account__c"  {
}
entity ProductPackageLoanHistory as "<b>Product Package Loan History</b> \nLLC_BI__Product_Package_Parent_Loan_History__c"  {
}
entity Loan as "<b>Loan</b> \nLLC_BI__Loan__c"  {
}
entity Review as "<b>Review</b> \nLLC_BI__Review__c"  {
}
entity EntityInvolvement as "<b>Entity Involvement</b> \nLLC_BI__Legal_Entities__c"  {
}
entity ReviewLoan as "<b>Review Loan</b> \nLLC_BI__Review_Loan__c"  {
}
entity Application as "<b>Application</b> \nLLC_BI__Application__c"  {
}
entity TreasuryService as "<b>Treasury Service</b> \nLLC_BI__Treasury_Service__c"  {
}
entity LoanTeamMember as "<b>Loan Team Member</b> \nLLC_BI__LoanTeam__c"  {
}
entity CreditMemo as "<b>Credit Memo</b> \nLLC_BI__Credit_Memo__c"  {
}
entity OpportunityHistory as "<b>Opportunity History</b> \nLLC_BI__Opportunity_History__c"  {
}

ProductPackageTeamMember }o--|| ProductPackage: M
Lead }o--o| Branch
ReviewAccount }o--o| Relationship
Loan }o--o| Relationship: x2
Deposit }o--o| Contact
Deposit }o--o| Branch
ReviewLoan }o--|| Review: M
Lead }o--o| Lead
Deposit }o--o| Deposit: x2
Loan }o--o| Loan: x3
AuthorizedSigner }o--o| AuthorizedSigner
Contact }o--o| Relationship
TreasuryService }o--o| Relationship
Opportunity }o--o| Relationship
Opportunity }o--o| Branch
Connection }o--o| ConnectionRole
Lead }o--o| Opportunity
AuthorizedSigner }o--|| Contact: M
Loan }o--o| Branch
Loan }o--o| CreditMemo
Opportunity }o--o| OpportunityHistory: x2
Lead }o--o| Contact
TreasuryService }o--o| CreditMemo
EntityInvolvement }o--o| Loan
Opportunity }o--o| Deposit
EntityInvolvement }o--o| ProductPackage
ProductPackage }o--o| Relationship: x2
ProductPackageLoanHistory }o--o| Loan: x3
Contact }o--o| Contact: x2
Relationship }o--o| Branch
OpportunityHistory }o--o| Deposit
Opportunity }o--o| Contact
Relationship }o--o| Relationship
ConnectionRole }o--o| ConnectionRole
Application }o--o| Relationship
Deposit }o--o| ProductPackage
Review }o--o| ProductPackage
Opportunity }o--o| Loan
Loan }o--o| Application
Connection }o--|| Relationship: M
Deposit }o--o| Relationship: x2
ReviewLoan }o--o| Loan
Opportunity }o--o| ProductPackage
EntityInvolvement }o--o| Relationship
OpportunityHistory }o--o| ProductPackage
EntityInvolvement }o--o| TreasuryService
TreasuryService }o--o| Application
Lead }o--o| Relationship: x2
Lead }o--o| ProductPackage
ReviewAccount }o--|| Review: M
EntityInvolvement }o--|| Relationship: M
LoanTeamMember }o--|| Loan: M
OpportunityHistory }o--o| Loan
Loan }o--o| Contact
Application }o--o| ProductPackage
TreasuryService }o--o| Branch
OpportunityHistory }o--o| TreasuryService
AuthorizedSigner }o--|| EntityInvolvement: M
TreasuryService }o--o| ProductPackage
Opportunity }o--o| Opportunity
Lead }o--o| Loan
Deposit }o--o| Application
Review }o--o| CreditMemo
EntityInvolvement }o--o| Deposit
Review }o--o| Relationship
Connection }o--|| Relationship
ProductPackage }o--o| CreditMemo
Loan }o--o| ProductPackage
ProductPackageLoanHistory }o--o| ProductPackage

@enduml
