@startuml
'https://plantuml.com/class-diagram

left header 28 objects
title nCino 2023 Fall - Document Manager Summary - AutoGen

'skinparam classBorderThickness 0

hide circle
hide empty methods
hide empty fields

'legend right
'  Relationship
'    M = MasterDetail
'    xn = n-times
'  Field
'    bold = required
'    underline = MasterDetail
'endlegend


entity ProductCCL as "<b>ProductCCL</b> \nLLC_BI__ProductCCL__c"  {
}
entity Product as "<b>Product</b> \nLLC_BI__Product__c"  {
}
entity ProductDocTab as "<b>ProductDocTab</b> \nLLC_BI__ProductDocTab__c"  {
}
entity DocTab as "<b>DocTab</b> \nLLC_BI__DocTab__c"  {
}
entity Deposit as "<b>Deposit</b> \nLLC_BI__Deposit__c"  {
}
entity DocumentPlaceholder as "<b>Document Placeholder</b> \nLLC_BI__Document_Placeholder__c"  {
}
entity AccountDocComment as "<b>AccountDocComment</b> \nLLC_BI__AccountDocComment__c"  {
}
entity AccountDocument as "<b>AccountDocument</b> \nLLC_BI__AccountDocument__c"  {
}
entity Relationship as "<b>Relationship</b> \nAccount" #lightblue {
}
entity DocumentStoreIndex as "<b>Document Store Index</b> \nLLC_BI__Document_Store_Index__c"  {
}
entity DocManager as "<b>DocManager</b> \nLLC_BI__DocManager__c"  {
}
entity DocType as "<b>DocType</b> \nLLC_BI__DocType__c"  {
}
entity Note as "<b>Note</b> \nNote" #lightblue {
}
entity User as "<b>User</b> \nUser" #lightblue {
}
entity DocumentStore as "<b>Document Store</b> \nLLC_BI__Document_Store__c"  {
}
entity DocumentVersion as "<b>Document Version</b> \nLLC_BI__Document_Version__c"  {
}
entity LoanDocumentName as "<b>Loan Document Name</b> \nLLC_BI__LLC_LoanDocument__c"  {
}
entity DocClass as "<b>DocClass</b> \nLLC_BI__DocClass__c"  {
}
entity ClosingChecklist as "<b>Closing Checklist</b> \nLLC_BI__ClosingChecklist__c"  {
}
entity CollateralTypeCCL as "<b>Collateral Type CCL</b> \nLLC_BI__Collateral_Type_CCL__c"  {
}
entity LLC_LoanDocComment as "<b>LLC_LoanDocComment</b> \nLLC_BI__LLC_LoanDocComment__c"  {
}
entity CollateralType as "<b>Collateral Type</b> \nLLC_BI__Collateral_Type__c"  {
}
entity Loan as "<b>Loan</b> \nLLC_BI__Loan__c"  {
}
entity ContentDocumentLink as "<b>Content Document Link</b> \nContentDocumentLink" #lightblue {
}
entity ContentDocument as "<b>Content Document</b> \nContentDocument" #lightblue {
}
entity ContentVersion as "<b>Content Version</b> \nContentVersion" #lightblue {
}
entity Attachment as "<b>Attachment</b> \nAttachment" #lightblue {
}
entity DocumentCollectionIndex as "<b>Document Collection Index</b> \nLLC_BI__Document_Collection_Index__c"  {
}

LoanDocumentName }o--o| DocManager
ClosingChecklist }o--o| DocType
Loan }o--o| Relationship: x2
DocumentPlaceholder }o--o| DocManager
DocTab }o--o| DocManager
DocumentPlaceholder }o--o| DocType
AccountDocument }o--o| DocTab
CollateralTypeCCL }o--|| ClosingChecklist: M
Deposit }o--o| Product
LoanDocumentName }o--|| Loan: M
ContentVersion }o--o| User
Deposit }o--o| Deposit: x2
Loan }o--o| Loan: x3
DocClass }o--|| DocType: M
LoanDocumentName }o--o| ClosingChecklist
DocumentPlaceholder }o--o| DocTab
DocumentPlaceholder }o--o| DocumentStoreIndex
CollateralType }o--o| CollateralType: x2
LoanDocumentName }o--o| DocumentStoreIndex
DocumentPlaceholder }o--o| ClosingChecklist
ProductDocTab }o--|| Product: M
ProductDocTab }o--|| DocTab: M
ProductCCL }o--|| Product: M
Loan }o--o| Product
LoanDocumentName }o--o| User: x3
LoanDocumentName }o--o| DocType
ContentVersion }o--|| User
Note }o--|| User
AccountDocument }o--o| AccountDocument
LoanDocumentName }o--o| DocClass
AccountDocument }o--o| User: x3
DocumentPlaceholder }o--o| Relationship
AccountDocument }o--o| DocManager
DocumentCollectionIndex }o--o| DocumentStore
DocClass }o--o| DocManager
DocType }o--o| DocTab
Relationship }o--o| Relationship
LoanDocumentName }o--o| DocTab
ContentDocumentLink }o--|| ContentDocument
ProductCCL }o--|| ClosingChecklist: M
Deposit }o--o| Relationship: x2
DocumentVersion }o--|| DocumentStore
LLC_LoanDocComment }o--|| LoanDocumentName: M
LoanDocumentName }o--o| LoanDocumentName
Loan }o--o| User: x5
CollateralTypeCCL }o--|| CollateralType: M
AccountDocument }o--o| DocumentStoreIndex
ContentDocument }o--|| User
DocumentPlaceholder }o--o| User: x3
ClosingChecklist }o--o| DocClass
Deposit }o--o| User
DocumentStoreIndex }o--|| DocumentStore
ContentVersion }o--|| ContentDocument
Relationship }o--|| User
AccountDocComment }o--|| AccountDocument: M
ClosingChecklist }o--o| DocTab
DocumentPlaceholder }o--o| DocClass
ContentDocument }o--o| User
AccountDocument }o--o| ClosingChecklist
ClosingChecklist }o--o| DocManager
AccountDocument }o--|| Relationship: M
ContentDocument }o--o| ContentVersion
DocumentPlaceholder }o--o| Deposit
AccountDocument }o--o| DocType
DocumentCollectionIndex }o--|| DocumentStore
DocType }o--o| DocManager
User }o--o| Relationship

@enduml
