@startuml
'https://plantuml.com/class-diagram

left header 7 objects
title nCino 2023 Fall - Fees Summary - AutoGen

'skinparam classBorderThickness 0

hide circle
hide empty methods
hide empty fields

'legend right
'  Relationship
'    M = MasterDetail
'    xn = n-times
'  Field
'    bold = required
'    underline = MasterDetail
'endlegend


entity Loan as "<b>Loan</b> \nLLC_BI__Loan__c"  {
}
entity ServiceMgmt as "<b>Service Mgmt</b> \nLLC_BI__Service_Mgmt__c"  {
}
entity ServiceMgmtDetail as "<b>Service Mgmt Detail</b> \nLLC_BI__Service_Mgmt_Detail__c"  {
}
entity Fee as "<b>Fee</b> \nLLC_BI__Fee__c"  {
}
entity FeeLoanAggregate as "<b>Fee Loan Aggregate</b> \nLLC_BI__Fee_Loan_Aggregate__c"  {
}
entity Relationship as "<b>Relationship</b> \nAccount" #lightblue {
}
entity TemplateRecords as "<b>Template Records</b> \nLLC_BI__Template_Records__c"  {
}

Fee }o--o| ServiceMgmtDetail
Loan }o--o| Relationship: x2
Fee }o--o| FeeLoanAggregate
Fee }o--o| Relationship
Loan }o--o| Loan: x3
Loan }o--o| FeeLoanAggregate
ServiceMgmt }o--o| Relationship: x2
Fee }o--|| Loan: M
ServiceMgmtDetail }o--|| ServiceMgmt: M
Fee }o--o| Fee
Relationship }o--o| Relationship
ServiceMgmt }o--o| Loan
Fee }o--o| TemplateRecords
ServiceMgmt }o--o| ServiceMgmt

@enduml
