@startuml
'https://plantuml.com/class-diagram

left header 12 objects
title nCino 2023 Fall - Risk Rating Summary - AutoGen

'skinparam classBorderThickness 0

hide circle
hide empty methods
hide empty fields

'legend right
'  Relationship
'    M = MasterDetail
'    xn = n-times
'  Field
'    bold = required
'    underline = MasterDetail
'endlegend


entity Product as "<b>Product</b> \nLLC_BI__Product__c"  {
}
entity ProductProgram as "<b>Product Program</b> \nLLC_BI__Product_Program__c"  {
}
entity ProductProgramHistoryDetail as "<b>Product Program History Detail</b> \nLLC_BI__Product_Program_History_Detail__c"  {
}
entity ProductProgramHistory as "<b>Product Program History</b> \nLLC_BI__Product_Program_History__c"  {
}
entity RiskGradingCriteria as "<b>Risk Grading Criteria</b> \nLLC_BI__Risk_Grade_Criteria__c"  {
}
entity RiskGradeFactor as "<b>Risk Grade Factor</b> \nLLC_BI__Risk_Grade_Factor__c"  {
}
entity RiskGradeFactorValue as "<b>Risk Grade Factor Value</b> \nLLC_BI__Risk_Grade_Factor_Value__c"  {
}
entity RiskGradeGroup as "<b>Risk Grade Group</b> \nLLC_BI__Risk_Grade_Group__c"  {
}
entity Loan as "<b>Loan</b> \nLLC_BI__Loan__c"  {
}
entity RiskRatingReview as "<b>Risk Rating Review</b> \nLLC_BI__Annual_Review__c"  {
}
entity Relationship as "<b>Relationship</b> \nAccount" #lightblue {
}
entity RiskGradeTemplate as "<b>Risk Grade Template</b> \nLLC_BI__Risk_Grade_Template__c"  {
}

ProductProgramHistoryDetail }o--o| ProductProgram
Loan }o--o| Relationship: x2
Loan }o--o| RiskGradeTemplate
RiskGradeFactor }o--o| RiskGradeGroup
RiskGradeFactorValue }o--o| RiskGradeTemplate
ProductProgramHistoryDetail }o--|| ProductProgramHistory: M
ProductProgram }o--o| ProductProgram
RiskGradeGroup }o--|| RiskGradeTemplate: M
RiskGradeFactor }o--o| RiskGradeTemplate
Loan }o--o| Loan: x3
RiskGradingCriteria }o--|| RiskGradeFactor: M
RiskRatingReview }o--|| Relationship: M
RiskGradeTemplate }o--o| RiskRatingReview
ProductProgramHistory }o--|| Loan: M
RiskGradeFactorValue }o--|| RiskGradeFactor: M
RiskRatingReview }o--o| Loan
ProductProgram }o--o| RiskGradeTemplate: x2
RiskGradeFactorValue }o--o| RiskRatingReview
Relationship }o--o| RiskGradeTemplate
ProductProgram }o--|| Product: M
Relationship }o--o| Relationship
RiskRatingReview }o--o| RiskGradeTemplate
Loan }o--o| Product

@enduml
