@startuml
'https://plantuml.com/class-diagram

left header 8 objects
title nCino 2023 Fall - Rate and Payment Summary - AutoGen

'skinparam classBorderThickness 0

hide circle
hide empty methods
hide empty fields

'legend right
'  Relationship
'    M = MasterDetail
'    xn = n-times
'  Field
'    bold = required
'    underline = MasterDetail
'endlegend


entity Rate as "<b>Rate</b> \nLLC_BI__Rate__c"  {
}
entity Index as "<b>Index</b> \nLLC_BI__Index__mdt"  {
}
entity PricingRateComponent as "<b>Pricing Rate Component</b> \nLLC_BI__Pricing_Rate_Component__c"  {
}
entity PricingCovenant as "<b>Pricing Covenant</b> \nLLC_BI__Pricing_Covenant__c"  {
}
entity Period as "<b>Period</b> \nLLC_BI__Period__mdt"  {
}
entity Loan as "<b>Loan</b> \nLLC_BI__Loan__c"  {
}
entity PricingStream as "<b>Pricing Stream</b> \nLLC_BI__Pricing_Stream__c"  {
}
entity PricingPaymentComponent as "<b>Pricing Payment Component</b> \nLLC_BI__Pricing_Payment_Component__c"  {
}

PricingStream }o--o| Loan
PricingRateComponent }o--|| PricingStream: M
PricingPaymentComponent }o--|| PricingStream: M
Loan }o--o| Loan: x3
PricingCovenant }o--|| PricingRateComponent: M
PricingPaymentComponent }o--o| PricingStream

@enduml
