@startuml
'https://plantuml.com/class-diagram

left header 14 objects
title nCino 2023 Fall - Consumer Loan Summary - AutoGen

'skinparam classBorderThickness 0

hide circle
hide empty methods
hide empty fields

'legend right
'  Relationship
'    M = MasterDetail
'    xn = n-times
'  Field
'    bold = required
'    underline = MasterDetail
'endlegend


entity Fee as "<b>Fee</b> \nLLC_BI__Fee__c"  {
}
entity FeeLoanAggregate as "<b>Fee Loan Aggregate</b> \nLLC_BI__Fee_Loan_Aggregate__c"  {
}
entity PricingOption as "<b>Pricing Option</b> \nLLC_BI__Pricing_Option__c"  {
}
entity LoanCompliance as "<b>Loan Compliance</b> \nLLC_BI__Loan_Compliance__c"  {
}
entity EntityInvolvement as "<b>Entity Involvement</b> \nLLC_BI__Legal_Entities__c"  {
}
entity Branch as "<b>Branch</b> \nLLC_BI__Branch__c"  {
}
entity Relationship as "<b>Relationship</b> \nAccount" #lightblue {
}
entity Loan as "<b>Loan</b> \nLLC_BI__Loan__c"  {
}
entity Product as "<b>Product</b> \nLLC_BI__Product__c"  {
}
entity ProductType as "<b>Product Type</b> \nLLC_BI__Product_Type__c"  {
}
entity ProductLine as "<b>Product Line</b> \nLLC_BI__Product_Line__c"  {
}
entity ProductFeature as "<b>Product Feature</b> \nLLC_BI__Product_Feature__c"  {
}
entity Contact as "<b>Contact</b> \nContact" #lightblue {
}
entity AdverseAction as "<b>Adverse Action</b> \nLLC_BI__Adverse_Action__c"  {
}

AdverseAction }o--|| Loan: M
Loan }o--o| Relationship: x2
Product }o--|| ProductType: M
Fee }o--o| Relationship
EntityInvolvement }o--o| Relationship
PricingOption }o--o| Relationship
Loan }o--o| Loan: x3
Contact }o--o| Relationship
Fee }o--o| PricingOption
LoanCompliance }o--o| Loan
EntityInvolvement }o--|| Relationship: M
Loan }o--o| Product
Loan }o--o| Branch
Fee }o--o| FeeLoanAggregate
Product }o--o| ProductFeature
Loan }o--o| Contact
PricingOption }o--o| Product
EntityInvolvement }o--o| Loan
PricingOption }o--o| FeeLoanAggregate
Loan }o--o| FeeLoanAggregate
PricingOption }o--o| Loan
Fee }o--|| Loan: M
Contact }o--o| Contact: x2
Fee }o--o| EntityInvolvement
Relationship }o--o| Branch
Loan }o--o| PricingOption
Fee }o--o| Fee
Relationship }o--o| Relationship
ProductType }o--|| ProductLine: M

@enduml
